# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFv3ZsS1DB-_YHVMrrafNbRu55UUf7q7

# 📊 Análise de Churn – Telecom X

Este notebook apresenta uma análise exploratória dos dados de clientes da empresa fictícia Telecom X, com foco na evasão de clientes (churn).
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## 🔍 Entendimento dos Dados

Nesta etapa, analisamos a estrutura inicial do conjunto de dados para compreender suas variáveis e tipos.

"""

# Exemplo de carregamento do dataset
# df = pd.read_csv('telecom_churn.csv')

# Visualização inicial (exemplo)
# df.head()

"""## 📈 Análise Exploratória

A análise exploratória visa identificar padrões entre clientes que cancelaram e os que permaneceram, considerando variáveis como tipo de contrato, tempo de permanência e valores cobrados.

## ✅ Conclusão

A análise indica que fatores como contratos mensais, menor tempo de permanência e maiores cobranças mensais estão associados a maiores taxas de churn.

Com base nesses insights, recomenda-se a criação de estratégias de retenção focadas em clientes com maior risco de evasão.
"""